
from .model import Predmet, Claass, Tema_test, Test, Temy_site
from .model import (
    add_predmet,
    add_claass,
    add_Tema_test,
    add_temy_site,
    find_temy_site,
    ob1_ob2,
    ob2_ob3,
    find_last_Tema_test,
    find_claass,
    find_Tema_test_by_id,
    find_temi_by_predmet,
    find_temi_by_test,
    find_test_to_slovo,
    mass_ans,
    tes_ans,
    find_test,
    first_tema_test,
    add_test,
    update_test,
    update_by_id,
    delete_by_id,
    find_by_id,
    get_all_items,
    delete_tema_test_and_tests,
    update_test_num_quest,
    find_last_test,
    min_max_test_id,
)
